Parse ellipses in Java keyword annotations
returntocorp/pfff pull request #254
Opened 2020-08-21 20:12 UTC by nbrahms

Allows the user to match a subset of keywords in a keyword annotation.

Fixes returntocorp/semgrep#522

2020-08-25 17:12 UTC, colleend commented on lang_java/parsing/ast_java.ml
> +   | AnnotArgPairInit of annotation_pair list * tok option
done!

2020-08-26 07:43 UTC, aryx commented
Hmm actually this will not allow the pattern grayson originally wrote:
@RequestMapping(..., method=$M, ...)
public $RETURN $METHOD(...) { ... }

This is because we allow ... at the beginning but not the end.
We also probably want to allow also @RequestMapping(...).

2020-08-26 07:45 UTC, aryx commented
There's different want to solve that.
We could add a new AnnotArgEllipsis in annotation_element and make annotation_pair a variant with
  AnnotPair of ident * element_value
| AnnotPairEllipsis of tok
and then extend the grammar accordingly.

2020-08-26 07:46 UTC, aryx requested changes
This will not support the semgrep pattern of grayson:
@RequestMapping(..., method=$M, ...)
public $RETURN $METHOD(...) { ... }

2020-08-26 22:57 UTC, colleend commented
> There's different want to solve that.
> We could add a new AnnotArgEllipsis in annotation_element and make annotation_pair a variant with
> AnnotPair of ident * element_value
> | AnnotPairEllipsis of tok
> and then extend the grammar accordingly.

sorry, why is it necessary to extend annotation_pair with AnnotPairEllipsis of tok? Is this so we can  support the case where there's ellipses on both sides?

2020-08-27 13:37 UTC, aryx commented
yes. Grayson semgrep.live example was using ... on both sides, and we support ... on both sides
in arguments, parameters, classes, etc. so there's no reason to not allow it in annotation arguments.

2020-08-28 00:16 UTC, colleend commented
I changed annotation_pair to a variant, but had to delete expr1's variant of "..." because this led to a reduce-reduce conflict :o 
@aryx if there's anything I can do to make the code cleaner, please feel free to tell me! 

Not sure if this is the correct direction, but did my best :)

2020-08-28 07:43 UTC, aryx approved these changes
Lookd good! I think it should work like that.

2020-08-28 16:10 UTC, merged

2020-08-28 16:15 UTC, minusworld commented
YESSSS