Derive hash functions for the generic AST
returntocorp/pfff pull request #381
Opened 2021-01-14 05:37 UTC by mjambon

This is meant for the caching optimizations in semgrep.

2021-01-14 06:25 UTC, mjambon commented
Please don't merge yet, since it will break semgrep-core.

2021-01-14 09:15 UTC, aryx approved these changes

2021-01-14 09:15 UTC, aryx commented
We could merge anyway since semgrep-core uses a pinned version of pfff.

2021-01-14 19:15 UTC, aryx approved these changes

2021-01-16 08:16 UTC, aryx requested changes

2021-01-16 08:16 UTC, aryx commented on lang_GENERIC_base/AST_generic.ml
> +  s: stmt_kind [@equal fun _a _b -> true] [@hash.ignore];
Cant do that as i explained on slack.

2021-01-20 08:33 UTC, aryx approved these changes
Looks good, but if you could remove the private keyword so CI does not fail
(or fix lang_ocaml/parsing/parser_ml.mly)

Is there a way you could move out some of the code out of AST_generic.ml?
I try to keep AST_generic.ml as small as possible and move helpers functions
out in AST_generic_helpers.ml when I can.

2021-01-20 08:33 UTC, aryx commented on lang_GENERIC_base/AST_generic.ml
> +  type t = private int [@@deriving show, eq, hash]
This is not supported by the ocaml parser in pfff, and so semgrep choke in CI. Can you do without
this advanced feature?

2021-01-20 09:39 UTC, aryx commented on lang_GENERIC_base/AST_generic.ml
> +      failwith "an equal is already in progress"
This busy trick is nice! I thought about using a global, but didn't think about how
to make sure we don't use both at the same time (e.g., in different threads or later different cores).

2021-01-26 08:24 UTC, aryx approved these changes
ok let's merge this!

2021-01-26 08:24 UTC, mjambon commented
There's a problem an ubuntu repo. Is this new?

2021-01-26 09:37 UTC, aryx approved these changes

2021-01-26 09:37 UTC, merged